### ISSUE TITLE
Make sure that player and enemies handle slopes/stepps correctly

### ISSUE THREAD

**Issue by Abb4** [cloudchasingmeerkat/laverna#30]
- [ ] document appropriate walkable/unwalkable **slope** height, if it didn't happen in #8 
- [ ] document appropriate walkable/unwalkable **steps** height, if it didn't happen in #8 
- [ ] maybe lay a "pyramid-collider" over the steps, instead of individual colliders
- [ ] make sure player can navigate over it, maybe create a demo level
- [ ] make sure KI can navigate over it, maybe create a demo level (especially chasing enemies: #11)
